### ISSUE TITLE
[Enhancement] More detailed loading

### ISSUE THREAD

**Issue by E0x72-21** [IAFEnvoy/EarlyLoadingBar#1]
Can the early loading bar be able to show more detailed information about the game launching progress? (like Forge's loading bar)

![image](https://github.com/user-attachments/assets/bd97ad3e-cf87-4311-8b74-ae87ffe61278)

**Comment by IAFEnvoy** [comment]
https://modrinth.com/mod/forge-early-loading-screen-fabric
